#define ATTACHTOP_PATCH 1

#define AUTOSTART_PATCH 1

#define NATURALSCROLLTRACKPAD_PATCH 1

#define PERTAG_PATCH 1

#define RESTORE_MONITOR_PATCH 1

#define VANITYGAPS_PATCH 1

#define WARPCURSOR_PATCH 1
