#define ATTACHTOP_PATCH 1

#define AUTOSTART_PATCH 1

#define FOREIGN_TOPLEVEL_MANAGEMENT_PATCH 1

#define IPC_PATCH 1

#define NATURALSCROLLTRACKPAD_PATCH 1

#define NUMLOCK_CAPSLOCK_PATCH 1

#define PERTAG_PATCH 1

#define RESTORE_MONITOR_PATCH 1

#define SETUPENV_PATCH 1

#define VANITYGAPS_PATCH 1

#define WARPCURSOR_PATCH 1
