#+TITLE: Personal dwl Configuration
#+AUTHOR: Sravan Balaji
#+AUTO_TANGLE: t
#+STARTUP: showeverything

* Table of Contents :TOC_3:noexport:
- [[#welcome][Welcome]]
- [[#dwl---dwm-for-wayland][dwl - dwm for Wayland]]
- [[#patches][Patches]]
  - [[#always-center][Always Center]]
  - [[#attach-top][Attach Top]]
  - [[#auto-start][Auto Start]]
  - [[#foreign-toplevel-management][Foreign Toplevel Management]]
  - [[#ipc][IPC]]
  - [[#natural-scroll-trackpad][Natural Scroll Trackpad]]
  - [[#numlock-capslock][Numlock Capslock]]
  - [[#per-tag][Per Tag]]
  - [[#restore-monitor][Restore Monitor]]
  - [[#setup-env][Setup Env]]
  - [[#vanity-gaps][Vanity Gaps]]
  - [[#warp-cursor][Warp Cursor]]
- [[#dwl-configuration][dwl Configuration]]
  - [[#appearance][Appearance]]
  - [[#tagging][Tagging]]
  - [[#logging][Logging]]
  - [[#environment-variables][Environment Variables]]
  - [[#autostart][Autostart]]
  - [[#window-rules][Window Rules]]
  - [[#layouts][Layouts]]
  - [[#monitor-rules][Monitor Rules]]
  - [[#keyboard][Keyboard]]
  - [[#trackpad][Trackpad]]
  - [[#keybindings][Keybindings]]
  - [[#commands][Commands]]
  - [[#buttons][Buttons]]
- [[#justfile][Justfile]]

* Welcome

My personal configuration of dwl, written as an [[https://orgmode.org][Org Mode]] document.

Run the block below with ~C-c C-c~ to tangle code blocks to config file.

#+BEGIN_SRC emacs-lisp :tangle no
(org-mode-restart)
(org-babel-tangle)
#+END_SRC

After making changes, run the following in a terminal to recompile.

#+BEGIN_SRC bash :tangle no
sudo make clean install
#+END_SRC

* dwl - dwm for Wayland

See [[./README.md][Upstream README]] for details on project.

* Patches

** [[https://codeberg.org/dwl/dwl-patches/src/branch/main/patches/alwayscenter][Always Center]]

Automatically center floating windows.

#+BEGIN_SRC c :tangle patches.def.h
#define ALWAYSCENTER_PATCH 1
#+END_SRC

** [[https://codeberg.org/dwl/dwl-patches/src/branch/main/patches/attachtop][Attach Top]]

This is a port of attachtop patch for dwm: https://dwm.suckless.org/patches/attachtop

New client attaches below the last master/on top of the stack.

Behavior feels very intuitive as it doesn't disrupt existing masters no matter the amount of them, it only pushes the clients in stack down.

#+BEGIN_SRC c :tangle patches.def.h
#define ATTACHTOP_PATCH 1
#+END_SRC

** [[https://codeberg.org/dwl/dwl-patches/src/branch/main/patches/autostart][Auto Start]]

Allow dwl to execute commands from autostart array in your config.h file. And when you exit dwl all processes from autostart array will be killed.

Note: Commands from array are executed using execvp(). So if you need to execute shell command you need to prefix it with "sh", "-c" (change sh to any shell you like).

#+BEGIN_SRC c :tangle patches.def.h
#define AUTOSTART_PATCH 1
#+END_SRC

** [[https://codeberg.org/dwl/dwl-patches/src/branch/main/patches/foreign-toplevel-management][Foreign Toplevel Management]]

Implement ~foreign-toplevel-management~, it add handlers for activate, close, fullscreen and destroy request events, it's missing minimize and maximize request handlers.

#+BEGIN_SRC c :tangle patches.def.h
#define FOREIGN_TOPLEVEL_MANAGEMENT_PATCH 1
#+END_SRC

** [[https://codeberg.org/dwl/dwl-patches/src/branch/main/patches/ipc][IPC]]

Largely based on [[https://sr.ht/~raphi/][raphi]]'s [[https://sr.ht/~raphi/somebar/][somebar]], this patch provides an ipc for wayland clients to get and set dwl state. The ipc is intended for status bars, but can also be scripted with tools like [[https://codeberg.org/notchoc/dwlmsg][dwlmsg]].

Status information to stdout is currently disabled as dwl tends to freeze. For now, ~dwlmsg -w~ should act as a drop-in replacement.

Note to [[https://codeberg.org/dwl/dwl-patches/src/branch/main/patches/pertag][pertag]] users: apply [[https://codeberg.org/dwl/dwl-patches/src/branch/main/patches/ipc/ipcpertag.patch][this]] for ipc tagsetting to work as expected

#+BEGIN_SRC c :tangle patches.def.h
#define IPC_PATCH 1
#+END_SRC

** [[https://codeberg.org/dwl/dwl-patches/src/branch/main/patches/naturalscrolltrackpad][Natural Scroll Trackpad]]

Set natural scrolling only for trackpads.

#+BEGIN_SRC c :tangle patches.def.h
#define NATURALSCROLLTRACKPAD_PATCH 1
#+END_SRC

** [[https://codeberg.org/dwl/dwl-patches/src/branch/main/patches/numlock-capslock][Numlock Capslock]]

Allows activating numlock or capslock at startup.

#+BEGIN_SRC c :tangle patches.def.h
#define NUMLOCK_CAPSLOCK_PATCH 1
#+END_SRC

** [[https://codeberg.org/dwl/dwl-patches/src/branch/main/patches/pertag][Per Tag]]

Makes layout, mwfact and nmaster individual for every tag.

#+BEGIN_SRC c :tangle patches.def.h
#define PERTAG_PATCH 1
#+END_SRC

** [[https://codeberg.org/dwl/dwl-patches/src/branch/main/patches/restore-monitor][Restore Monitor]]

Moves clients to their old output when it is reattached.

#+BEGIN_SRC c :tangle patches.def.h
#define RESTORE_MONITOR_PATCH 1
#+END_SRC

** [[https://codeberg.org/dwl/dwl-patches/src/branch/main/patches/setupenv][Setup Env]]

Allow configuring environment variables in config.h

#+BEGIN_SRC c :tangle patches.def.h
#define SETUPENV_PATCH 1
#+END_SRC

** [[https://codeberg.org/dwl/dwl-patches/src/branch/main/patches/vanitygaps][Vanity Gaps]]

Adds (inner) gaps between client windows and (outer) gaps between windows and the screen edge in a flexible manner.

#+BEGIN_SRC c :tangle patches.def.h
#define VANITYGAPS_PATCH 1
#+END_SRC

** [[https://codeberg.org/dwl/dwl-patches/src/branch/main/patches/warpcursor][Warp Cursor]]

Warp cursor to the centre of newly focused clients.

Only moves the cursor if the cursor is currently not on the new client.

This is my version of the orphaned cursorwarp patch except I left out the config flag as I think it is unnecessary.

#+BEGIN_SRC c :tangle patches.def.h
#define WARPCURSOR_PATCH 1
#+END_SRC

* dwl Configuration

Taken from https://github.com/djpohly/dwl/issues/466.

** Appearance

#+BEGIN_SRC c :tangle config.h
#define COLOR(hex)    { ((hex >> 24) & 0xFF) / 255.0f, \
                        ((hex >> 16) & 0xFF) / 255.0f, \
                        ((hex >> 8) & 0xFF) / 255.0f, \
                        (hex & 0xFF) / 255.0f }
#+END_SRC

#+BEGIN_SRC c :tangle config.h
static const int sloppyfocus               = 1;  /* focus follows mouse */
static const int bypass_surface_visibility = 0;  /* 1 means idle inhibitors will disable idle tracking even if it's surface isn't visible  */
#if VANITYGAPS_PATCH
static const int smartgaps                 = 0;  /* 1 means no outer gap when there is only one window */
static const int monoclegaps               = 0;  /* 1 means outer gaps in monocle layout */
#endif // VANITYGAPS_PATCH
static const unsigned int borderpx         = 2;  /* border pixel of windows */
#if VANITYGAPS_PATCH
static const unsigned int gappih           = 20; /* horiz inner gap between windows */
static const unsigned int gappiv           = 20; /* vert inner gap between windows */
static const unsigned int gappoh           = 30; /* horiz outer gap between windows and screen edge */
static const unsigned int gappov           = 30; /* vert outer gap between windows and screen edge */
#endif // VANITYGAPS_PATCH
static const float rootcolor[]             = COLOR(0x282a36ff);
static const float bordercolor[]           = COLOR(0x4d4d4dff);
static const float focuscolor[]            = COLOR(0xbd93f9ff);
static const float urgentcolor[]           = COLOR(0xff5555ff);
/* This conforms to the xdg-protocol. Set the alpha to zero to restore the old behavior */
static const float fullscreen_bg[]         = {0.1f, 0.1f, 0.1f, 1.0f}; /* You can also use glsl colors */
#+END_SRC

** Tagging

#+BEGIN_SRC c :tangle config.h
/* tagging - TAGCOUNT must be no greater than 31 */
#define TAGCOUNT (9)
#+END_SRC

** Logging

#+BEGIN_SRC c :tangle config.h
static int log_level = WLR_ERROR;
#+END_SRC

** Environment Variables
#+BEGIN_SRC c :tangle config.h
#if SETUPENV_PATCH
static const Env envs[] = {
	/* variable                      value */
	{ "TERM",                        "xterm-256color" },
	{ "SHELL",                       "/bin/fish" },
	{ "EDITOR",                      "emacs" },
	{ "GIT_EDITOR",                  "emacs" },
	{ "BROWSER",                     "vivaldi-stable" },
	{ "QT_QPA_PLATFORMTHEME",        "qt6ct" },
	{ "_JAVA_AWT_WM_NONREPARENTING", "1" },
	{ "XDG_CURRENT_DESKTOP",         "wlroots" },
};
#endif // SETUPENV_PATCH
#+END_SRC

** Autostart

#+BEGIN_SRC c :tangle config.h
#if AUTOSTART_PATCH
static const char *const autostart[] = {
        /* Display / Compositor Setup */
        "/usr/bin/shikane", NULL,
        "/usr/bin/bash", "/home/sravan/.azotebg", NULL,
        "/usr/bin/gammastep", "-x", NULL,
        /* Background Processes */
        "/usr/libexec/polkit-gnome-authentication-agent-1", NULL,
        "/usr/bin/kdeconnectd", "--replace", NULL,
        "/usr/bin/bash", "/home/sravan/.scripts/dunst.sh", "--on", NULL,
        "/usr/bin/wl-paste", "--type", "text", "--watch", "cliphist", "store", NULL,
        "/usr/bin/wl-paste", "--type", "image", "--watch", "cliphist", "store", NULL,
        /* Tray Applications */
        "/usr/bin/gammastep-indicator", NULL,
        "/usr/bin/blueman-applet", NULL,
        "/usr/bin/nm-applet", NULL,
        "/usr/bin/kdeconnect-indicator", NULL,
        "/usr/bin/flameshot", NULL,
        "/usr/bin/udiskie", "-a", "-n", "-s", NULL,
        /* GUI Applications */
        "/usr/bin/nextcloud", NULL,
        "/usr/bin/syncthing-gtk", NULL,
        "/usr/bin/openrgb", NULL,
        NULL /* terminate */
};
#endif // AUTOSTART_PATCH
#+END_SRC

** Window Rules

#+BEGIN_SRC c :tangle config.h
/* NOTE: ALWAYS keep a rule declared even if you don't use rules (e.g leave at least one example) */
static const Rule rules[] = {
	/* app_id             title       tags mask     isfloating   monitor */
	/* examples: */
	{ "Gimp_EXAMPLE",     NULL,       0,            1,           -1 }, /* Start on currently visible tags floating, not tiled */
	{ "firefox_EXAMPLE",  NULL,       1 << 8,       0,           -1 }, /* Start on ONLY tag "9" */
};
#+END_SRC

** Layouts

#+BEGIN_SRC c :tangle config.h
static const Layout layouts[] = {
	/* symbol     arrange function */
	{ "[]=",      tile },
	{ "><>",      NULL },    /* no layout function means floating behavior */
	{ "[M]",      monocle },
};
#+END_SRC

** Monitor Rules

#+BEGIN_SRC c :tangle config.h
/* (x=-1, y=-1) is reserved as an "autoconfigure" monitor position indicator
 ,* WARNING: negative values other than (-1, -1) cause problems with Xwayland clients
 ,* https://gitlab.freedesktop.org/xorg/xserver/-/issues/899
,*/
/* NOTE: ALWAYS add a fallback rule, even if you are completely sure it won't be used */
static const MonitorRule monrules[] = {
	/* name       mfact  nmaster scale layout       rotate/reflect                x    y */
	/* example of a HiDPI laptop monitor:
	{ "eDP-1",    0.5f,  1,      2,    &layouts[0], WL_OUTPUT_TRANSFORM_NORMAL,   -1,  -1 },
	,*/
	/* defaults */
	{ NULL,       0.5f, 1,      1,    &layouts[0], WL_OUTPUT_TRANSFORM_NORMAL,   -1,  -1 },
};
#+END_SRC

** Keyboard

#+BEGIN_SRC c :tangle config.h
static const struct xkb_rule_names xkb_rules = {
	/* can specify fields: rules, model, layout, variant, options */
	/* example:
	.options = "ctrl:nocaps",
	,*/
	.options = NULL,
};

#if NUMLOCK_CAPSLOCK_PATCH
/* numlock and capslock */
static const int numlock = 1;
static const int capslock = 0;
#endif // NUMLOCK_CAPSLOCK_PATCH

static const int repeat_rate = 25;
static const int repeat_delay = 600;
#+END_SRC

** Trackpad

#+BEGIN_SRC c :tangle config.h
static const int tap_to_click = 1;
static const int tap_and_drag = 1;
static const int drag_lock = 1;
static const int natural_scrolling = 1;
static const int disable_while_typing = 1;
static const int left_handed = 0;
static const int middle_button_emulation = 0;

/* You can choose between:
LIBINPUT_CONFIG_SCROLL_NO_SCROLL
LIBINPUT_CONFIG_SCROLL_2FG
LIBINPUT_CONFIG_SCROLL_EDGE
LIBINPUT_CONFIG_SCROLL_ON_BUTTON_DOWN
,*/
static const enum libinput_config_scroll_method scroll_method = LIBINPUT_CONFIG_SCROLL_2FG;

/* You can choose between:
LIBINPUT_CONFIG_CLICK_METHOD_NONE
LIBINPUT_CONFIG_CLICK_METHOD_BUTTON_AREAS
LIBINPUT_CONFIG_CLICK_METHOD_CLICKFINGER
,*/
static const enum libinput_config_click_method click_method = LIBINPUT_CONFIG_CLICK_METHOD_BUTTON_AREAS;

/* You can choose between:
LIBINPUT_CONFIG_SEND_EVENTS_ENABLED
LIBINPUT_CONFIG_SEND_EVENTS_DISABLED
LIBINPUT_CONFIG_SEND_EVENTS_DISABLED_ON_EXTERNAL_MOUSE
,*/
static const uint32_t send_events_mode = LIBINPUT_CONFIG_SEND_EVENTS_ENABLED;

/* You can choose between:
LIBINPUT_CONFIG_ACCEL_PROFILE_FLAT
LIBINPUT_CONFIG_ACCEL_PROFILE_ADAPTIVE
,*/
static const enum libinput_config_accel_profile accel_profile = LIBINPUT_CONFIG_ACCEL_PROFILE_ADAPTIVE;
static const double accel_speed = 0.0;

/* You can choose between:
LIBINPUT_CONFIG_TAP_MAP_LRM -- 1/2/3 finger tap maps to left/right/middle
LIBINPUT_CONFIG_TAP_MAP_LMR -- 1/2/3 finger tap maps to left/middle/right
,*/
static const enum libinput_config_tap_button_map button_map = LIBINPUT_CONFIG_TAP_MAP_LRM;
#+END_SRC

** Keybindings

#+BEGIN_SRC c :tangle config.h
/* If you want to use the windows key for MODKEY, use WLR_MODIFIER_LOGO */
#define MODKEY WLR_MODIFIER_LOGO

#define TAGKEYS(KEY,SKEY,TAG) \
	{ MODKEY,                    KEY,            view,            {.ui = 1 << TAG} }, \
	{ MODKEY|WLR_MODIFIER_CTRL,  KEY,            toggleview,      {.ui = 1 << TAG} }, \
	{ MODKEY|WLR_MODIFIER_SHIFT, SKEY,           tag,             {.ui = 1 << TAG} }, \
	{ MODKEY|WLR_MODIFIER_CTRL|WLR_MODIFIER_SHIFT,SKEY,toggletag, {.ui = 1 << TAG} }

/* helper for spawning shell commands in the pre dwm-5.0 fashion */
#define SHCMD(cmd) { .v = (const char*[]){ "/bin/sh", "-c", cmd, NULL } }
#+END_SRC

** Commands

#+BEGIN_SRC c :tangle config.h
static const char *termcmd[]         = { "kitty", NULL };
static const char *menucmd[]         = { "rofi", "-show", "combi", NULL };

static const Key keys[] = {
	/* Note that Shift changes certain key codes: c -> C, 2 -> at, etc. */
	/* modifier                  key                 function        argument */
	{ MODKEY,                    XKB_KEY_p,          spawn,          {.v = menucmd} },
	{ MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_Return,     spawn,          {.v = termcmd} },
#if IPC_PATCH
	{ MODKEY,                    XKB_KEY_b,          togglebar,      {0} },
#endif // IPC_PATCH
	{ MODKEY,                    XKB_KEY_j,          focusstack,     {.i = +1} },
	{ MODKEY,                    XKB_KEY_k,          focusstack,     {.i = -1} },
	{ MODKEY,                    XKB_KEY_i,          incnmaster,     {.i = +1} },
	{ MODKEY,                    XKB_KEY_d,          incnmaster,     {.i = -1} },
	{ MODKEY,                    XKB_KEY_h,          setmfact,       {.f = -0.05f} },
	{ MODKEY,                    XKB_KEY_l,          setmfact,       {.f = +0.05f} },
#if VANITYGAPS_PATCH
    { MODKEY|WLR_MODIFIER_ALT,   XKB_KEY_h,          incgaps,       {.i = +1 } },
    { MODKEY|WLR_MODIFIER_ALT,   XKB_KEY_l,          incgaps,       {.i = -1 } },
	{ MODKEY|WLR_MODIFIER_ALT|WLR_MODIFIER_SHIFT,   XKB_KEY_H,      incogaps,      {.i = +1 } },
	{ MODKEY|WLR_MODIFIER_ALT|WLR_MODIFIER_SHIFT,   XKB_KEY_L,      incogaps,      {.i = -1 } },
	{ MODKEY|WLR_MODIFIER_ALT|WLR_MODIFIER_CTRL,    XKB_KEY_h,      incigaps,      {.i = +1 } },
	{ MODKEY|WLR_MODIFIER_ALT|WLR_MODIFIER_CTRL,    XKB_KEY_l,      incigaps,      {.i = -1 } },
	{ MODKEY|WLR_MODIFIER_ALT,  XKB_KEY_0,          togglegaps,     {0} },
	{ MODKEY|WLR_MODIFIER_ALT|WLR_MODIFIER_SHIFT,   XKB_KEY_parenright,defaultgaps,    {0} },
	{ MODKEY,                    XKB_KEY_y,          incihgaps,     {.i = +1 } },
	{ MODKEY,                    XKB_KEY_o,          incihgaps,     {.i = -1 } },
	{ MODKEY|WLR_MODIFIER_CTRL,  XKB_KEY_y,          incivgaps,     {.i = +1 } },
	{ MODKEY|WLR_MODIFIER_CTRL,  XKB_KEY_o,          incivgaps,     {.i = -1 } },
	{ MODKEY|WLR_MODIFIER_ALT,   XKB_KEY_y,          incohgaps,     {.i = +1 } },
	{ MODKEY|WLR_MODIFIER_ALT,   XKB_KEY_o,          incohgaps,     {.i = -1 } },
	{ MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_Y,          incovgaps,     {.i = +1 } },
	{ MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_O,          incovgaps,     {.i = -1 } },
#endif // VANITYGAPS_PATCH
	{ MODKEY,                    XKB_KEY_Return,     zoom,           {0} },
	{ MODKEY,                    XKB_KEY_Tab,        view,           {0} },
	{ MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_C,          killclient,     {0} },
	{ MODKEY,                    XKB_KEY_t,          setlayout,      {.v = &layouts[0]} },
	{ MODKEY,                    XKB_KEY_f,          setlayout,      {.v = &layouts[1]} },
	{ MODKEY,                    XKB_KEY_m,          setlayout,      {.v = &layouts[2]} },
	{ MODKEY,                    XKB_KEY_space,      setlayout,      {0} },
	{ MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_space,      togglefloating, {0} },
	{ MODKEY,                    XKB_KEY_e,         togglefullscreen, {0} },
	{ MODKEY,                    XKB_KEY_0,          view,           {.ui = ~0} },
	{ MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_parenright, tag,            {.ui = ~0} },
	{ MODKEY,                    XKB_KEY_comma,      focusmon,       {.i = WLR_DIRECTION_LEFT} },
	{ MODKEY,                    XKB_KEY_period,     focusmon,       {.i = WLR_DIRECTION_RIGHT} },
	{ MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_less,       tagmon,         {.i = WLR_DIRECTION_LEFT} },
	{ MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_greater,    tagmon,         {.i = WLR_DIRECTION_RIGHT} },
	TAGKEYS(          XKB_KEY_1, XKB_KEY_exclam,                     0),
	TAGKEYS(          XKB_KEY_2, XKB_KEY_at,                         1),
	TAGKEYS(          XKB_KEY_3, XKB_KEY_numbersign,                 2),
	TAGKEYS(          XKB_KEY_4, XKB_KEY_dollar,                     3),
	TAGKEYS(          XKB_KEY_5, XKB_KEY_percent,                    4),
	TAGKEYS(          XKB_KEY_6, XKB_KEY_asciicircum,                5),
	TAGKEYS(          XKB_KEY_7, XKB_KEY_ampersand,                  6),
	TAGKEYS(          XKB_KEY_8, XKB_KEY_asterisk,                   7),
	TAGKEYS(          XKB_KEY_9, XKB_KEY_parenleft,                  8),
	{ MODKEY|WLR_MODIFIER_SHIFT, XKB_KEY_Q,          quit,           {0} },

	/* Ctrl-Alt-Backspace and Ctrl-Alt-Fx used to be handled by X server */
	{ WLR_MODIFIER_CTRL|WLR_MODIFIER_ALT,XKB_KEY_Terminate_Server, quit, {0} },
	/* Ctrl-Alt-Fx is used to switch to another VT, if you don't know what a VT is
	 ,* do not remove them.
	 ,*/
#define CHVT(n) { WLR_MODIFIER_CTRL|WLR_MODIFIER_ALT,XKB_KEY_XF86Switch_VT_##n, chvt, {.ui = (n)} }
	CHVT(1), CHVT(2), CHVT(3), CHVT(4), CHVT(5), CHVT(6),
	CHVT(7), CHVT(8), CHVT(9), CHVT(10), CHVT(11), CHVT(12),
};
#+END_SRC

** Buttons

#+BEGIN_SRC c :tangle config.h
static const Button buttons[] = {
	{ MODKEY, BTN_LEFT,   moveresize,     {.ui = CurMove} },
	{ MODKEY, BTN_MIDDLE, togglefloating, {0} },
	{ MODKEY, BTN_RIGHT,  moveresize,     {.ui = CurResize} },
};
#+END_SRC

* Justfile

#+BEGIN_SRC just :tangle justfile
set shell := ["bash", "-c"]

# List just commands by default
default:
    @just --list

# Rebuild project
dwl-rebuild:
    sudo make clean all
#+END_SRC
